site_name: Chtholly's Home
site_url: https://chtholly-boss.github.io/Chtholly-Boss/
theme:
    name: material

plugins:
    - search
    - blog

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
