site_name: Chtholly's Home
site_url: https://chtholly-boss.github.io/Chtholly-Boss/

theme:
    name: material

nav:
    - Home: index.md
    - Blog: 
        - blog/index.md
        - TAG board: blog/tags.md

plugins:
    - search
    - blog:
        archive: false
        categories_name: Categories
        categories_allowed:
            - Tools
            - Readings
            - Programming
    - tags:
        tags_file: blog/tags.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
